- app/Http/Controllers/Api/SaqController.php
- react/src/views/Admin.jsx
- routes/api.php
Compteurs ( inserer et doublons)
Minuteurs ( voir le temps de FetchProducts)
> Ajout de compteurs

- app/Http/Controllers/Api/SaqController.php
Retrait de tout ce qui viens apres extensions.
> Modifications de l'url de l'image

- app/Http/Controllers/Api/SaqController.php
- react/src/views/Admin.jsx
- routes/api.php
Ajout d'une fonctionnalités de progressBar
Version initial.
Optimisation a suivre.
> ProgressBar v1.01

- app/Http/Controllers/Api/SaqController.php
- database/migrations/2023_04_18_210103_create_bottles.php
- react/src/views/Admin.jsx
Implémentation, style et optimisation partielle du progressBar
Modiifcation de FetchProduits pour obtention du catalogue complet
> ProgressBar V2 + full fetch

- react/src/components/EditQuantityModal/EditQuantityModal.jsx
- react/src/components/ProductCard/ProductCard.jsx
Ajustment pour la carte produit
> CSS pour la carte de modification des quantitées et carte produit

- app/Http/Controllers/Api/SaqController.php
Commit manquant lors du dernier pull ProgressBar V2 + full fetch #75
> update pour fetch complet

- app/Http/Controllers/Api/SaqController.php
- database/factories/CountryFactory.php
- database/factories/FormatFactory.php
- database/factories/TypeFactory.php
- database/migrations/2023_04_18_210103_create_bottles.php
- database/migrations/2023_04_18_210228_create_countries.php
- database/migrations/2023_04_18_210237_create_formats.php
- database/migrations/2023_04_18_210259_create_types.php
- database/seeders/DatabaseSeeder.php
- react/src/views/Admin.jsx
Ajout de seeder pour standardisé le processurs.
Seeders obsolète puisque j'ai développer une logique directement lors du peuplage de bottles.
Regarde a travers les différentes table pour les clefs étrangères.
S'il n'existe pas il sont créer.
Peuplement dynamique.
> Standardisation des clefs et table étrangères pour fetch complet

- app/Http/Controllers/Api/SaqController.php
- app/Models/Bottle.php
- database/migrations/2023_04_18_210103_create_bottles.php
Ajout des fonctionnalités du crawler.
Ratings et num_comments
Retrait des colonnes jugé désuets.
> Optimisation du cURL et tables bottles

- app/Http/Controllers/Api/SaqController.php
- app/Models/Format.php
- database/factories/FormatFactory.php
- database/factories/TypeFactory.php
- database/migrations/2023_04_18_210237_create_formats.php
Suivis de logique afin de standardisé la deuxieme colonnes de nos tables en lien avec bottles.
Creation de fonctionnallités dynamique dans SaqController.php
> Standardisation de colonnes name

- app/Console/Kernel.php
- app/Http/Controllers/Api/SaqController.php
- app/Jobs/FetchProductsJob.php
Ajout de fonction automatisé (jobs) qui lancera la fonction fetchProducts
2x par semaine , les mercredi et dimanches a 3:30 am.
> Ajout de fonctionnalié (fetchProductsJobs)

- routes/api.php
le token d'authaurisation ne semble pas être mis en place dans le header de la requete (es. fetch/saq
> Rollback de la protection de certaines routes

- app/Http/Controllers/Api/SaqCatalogueController.php
- app/Http/Controllers/Api/SaqProductController.php
- app/Models/Bottle.php
- database/migrations/2023_04_18_210103_create_bottles.php
- resources/views/saq.blade.php
- routes/api.php
- routes/web.php
Creation du Crawler supplémentaires pour l'ajout de données supplémentaires a notre table bottles.
Traitement brute des données.
> Creation du Crawler supplémentaires(pageProduits)

- react/src/views/Catalog/Catalog.jsx
la pagination fonctionne maintenant avec les filtres, la recherche et ne donne pas d'erreur 'too many requests' lorsqu'on arrive a la fin des resultats ou les resultats sont petits (2 a 3). erreur de sentinel present sur la page allait chercher les bouteilles a l'infini
> pagination fix with search, filters and fetch loop error

- app/Http/Controllers/Api/SaqCatalogueController.php
- database/migrations/2023_04_18_210103_create_bottles.php
Version stable pour les deux crawlers a 300pages de produits
> 300 pages , 7k+ 2crawl test & validated 

- app/Http/Resources/BottleResource.php
- app/Models/Bottle.php
- react/src/components/ProductCard/ProductCard.jsx
- react/src/views/Product/ProductView.jsx
Gestion de l'affichage si il manque une ou des informations Modification CSS pour l'affichage de l'image de fond dans la page produit Ajout d'un padding en bas de la page produit
> Ajout de toutes les informations pour la bouteille

- app/Http/Resources/BottleResource.php
- app/Models/Cepage.php
> gestion clé étrangère nullable dans l'objet bottle

- app/Http/Resources/BottleResource.php
- app/Models/Bottle.php
- react/src/components/ProductCard/ProductCard.jsx
Pour optimiser la requête determinant si la bouteille est wishlisted
> Ajout de la relation wishlist() dans bottle

- app/Models/User.php
- database/migrations/2014_10_12_000000_create_users_table.php
- database/migrations/2023_05_09_131524_create_user_types_table.php
- database/seeders/UserTypesSeeder.php
Ajout d'une table user_types afin de donner des privilèges a certains utilisateurs.
Retrait de colonnes obsoletes.
Modifications model(user) et migrations (user et user_types).
> Ajout et modificatiosn Database

- app/Http/Controllers/Api/UserController.php
- app/Models/UserType.php
- package-lock.json
- package.json
- react/src/components/Stats/dataSet.jsx
- react/src/views/Admin.jsx
- routes/api.php
Modifications de la page Admin.jsx
Insertion d'onglet pour traiter ( stats et users)
Ajout des fonctionnalités et logique de base (fonctionnel) pour la modification des privileges sur un users.
-- Style temporaire, a modifier une fois les fonctionnalités consolidés.
> Modifications pannel Admin & function modifications User

- react/src/components/Stats/dataSet.jsx
- react/src/components/Stats/premierDataSet.jsx
- react/src/components/Stats/secondDataSet.jsx
- react/src/views/Admin.jsx
Ajout de second dataset.
Modification temporaire des type de chart
> Pannel Admin - stats tab

- app/Http/Controllers/Api/CellarHasBottleController.php
- package-lock.json
- package.json
- react/package-lock.json
- react/package.json
- react/src/components/EditQuantityModal/EditQuantityModal.jsx
- react/src/components/ProductCard/ProductCard.jsx
- react/src/views/Catalog/Catalog.jsx
avec message de succes dans le retour de recherche
> add custom quantity to cellar + add additional bottles

- react/src/components/Filter/FilterPanel.jsx
> Ajout d'un bouton 'cancel' dans filtre

- app/Http/Controllers/Api/LineGraphController.php
- app/Http/Controllers/Api/PieGraphController.php
- app/Http/Controllers/Api/QuickStatsController.php
- app/Http/Controllers/Api/StatsController.php
- react/src/components/Stats/DataSetB.jsx
- react/src/components/Stats/WineTypeAvg.jsx
- routes/api.php
--fix errreur de logique pour QuickStats( ajout de quantity dans l'equation).
Squelette et stucture de base pour le branchement des pieCHarts
> Connexion, stats & api

- app/Http/Controllers/Api/LineGraphController.php
- app/Http/Controllers/Api/PieGraphController.php
- composer.json
- composer.lock
- react/package-lock.json
- react/package.json
- react/src/components/Stats/DataSetA.jsx
- react/src/components/Stats/DataSetB.jsx
- react/src/components/Stats/DataSetC.jsx
- react/src/components/Stats/WineTypeAvg.jsx
- react/src/views/Admin.jsx
- routes/api.php
Plusieurs modifications dans la structure et le render des fichiers.
Touts les méthodes afin d'obtenir les données voulues.
Render et display des données recu avec react-chart-js.
Ajout de % ( a revoir )
> Branchemement API et requêtes eloquent pour Statistiques

- react/src/components/Stats/DataSetB.jsx
- react/src/components/Stats/DataSetC.jsx
Quelques modifications esthétiques mineur.
Reste encore beaucoup de travail.
> Modifications esthétique mineur /admin

- app/Http/Controllers/Api/QuickStatsController.php
- app/Http/Controllers/Api/UserController.php
- react/src/components/Stats/LinePlotChart.jsx
- react/src/components/Stats/PieCharts.jsx
- react/src/components/Stats/QuickStats.jsx
- react/src/components/Stats/TopWinePieChart.jsx
- react/src/views/Admin.jsx
- routes/api.php
- Completion de touts les fonctionnalités Admin
-Changement d'ordres des tables.
-standardisation des labels statistique
-ajout de methode userDelete
-modifications cartes user et modal user
> Fonctionnalités et esthétisme pannel /admin

- react/src/components/Stats/LinePlotChart.jsx
- react/src/views/Admin.jsx
Modifications esthétiques concernant le pannel Admin.
Marge, padding, titre et label.
Ajout de message de validations sur les opérations
> Ajustement esthétique final de /admin

- app/Http/Controllers/Api/LineGraphController.php
- database/factories/CellarFactory.php
- database/factories/CellarHasBottleFactory.php
- database/factories/UserFactory.php
- database/seeders/CellarHasBottleSeeder.php
- database/seeders/CellarSeeder.php
- database/seeders/UserSeeder.php
- react/src/components/Stats/QuickStats.jsx
- mis a jour/ creation seeders/factories pour avoir des statistiques intéréssante
- fix quelques erreurs de logique sur le retour des méthodes
- fix quelques faute esthétiques sur le rendu des données.
> Ajout de factory and seeding pour stats

- react/src/components/TopNavbar/TopNavbar.jsx
> suppression searchBar dans /users

- react/src/components/ProductCard/ProductCard.jsx
- react/src/views/Product/ProductView.jsx
> réponse front end immédiate
